### ISSUE TITLE
Implement exit(); method and item based endings

### ISSUE THREAD

**Issue by arnoao1** [arnoao1/hazel-and-friends-fork#21]
Items ( for reference): (if crossed out, item is already used for something else and not ideal for ending)
~~Soap~~
~~Flashlight~~
~~Food~~
*Water
*Vest
*Guard Gun
*Key
~~Keycard~~
*Rifle

**Comment by arnoao1** [comment]
--Renamed Guard Gun to Pistol

**Comment by arnoao1** [comment]
--All item names changed to all lowercase to prevent errors

**Comment by arnoao1** [comment]
exit(); should have an ending that uses 'key' acquired from dying prisoner near the start of the game, e.g. the key unlocks a door that lets you escape the prison.

**Comment by arnoao1** [comment]
Rifle:
You try to shoot your way out and the gun backfires and kills you ( died(); )
Key:
You sneak past the zombies and unlock the door
Water:
you drink the water then the zombies eat you 
Vest:
The zombies can't bite through your bulletproof vest, instead they bite your head, arms, and legs ( died(); )
Guard Gun:
you try to shoot your way out, you kill all the zombies and leave the jail

**Comment by batcsg1** [comment]
Within the exit method, the user is now able to decide whether or not to play the game again.

**Comment by batcsg1** [comment]
Implemented item-based endings within the exit method and depending on what item has been selected they will receive a message.
